version: '3'

services:
  app1:
    build:
      context: ./app
    container_name: app1
    expose:
      - "3000"

  app2:
    build:
      context: ./app
    container_name: app2
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2 